import { VoiceLanguage, VoicePersona } from '../types';

export const ALL_VOICE_LANGUAGES: { id: VoiceLanguage; label: string; flag: string; nativeName: string }[] = [
  { id: 'en-US', label: 'English (US)', flag: '🇺🇸', nativeName: 'English (United States)' },
  { id: 'en-GB', label: 'English (UK)', flag: '🇬🇧', nativeName: 'English (United Kingdom)' },
  { id: 'en-IN', label: 'English (India)', flag: '🇮🇳', nativeName: 'English (Indian Accent)' },
  { id: 'ur-PK', label: 'Urdu (Pakistan)', flag: '🇵🇰', nativeName: 'اردو' },
  { id: 'hi-IN', label: 'Hindi (India)', flag: '🇮🇳', nativeName: 'हिन्दी' },
  { id: 'es-ES', label: 'Spanish (Spain)', flag: '🇪🇸', nativeName: 'Español (España)' },
  { id: 'es-MX', label: 'Spanish (Mexico)', flag: '🇲🇽', nativeName: 'Español (México)' },
  { id: 'pt-BR', label: 'Portuguese (Brazil)', flag: '🇧🇷', nativeName: 'Português (Brasil)' },
  { id: 'pt-PT', label: 'Portuguese (Portugal)', flag: '🇵🇹', nativeName: 'Português (Portugal)' },
  { id: 'de-DE', label: 'German (Germany)', flag: '🇩🇪', nativeName: 'Deutsch' },
  { id: 'fr-FR', label: 'French (France)', flag: '🇫🇷', nativeName: 'Français' },
  { id: 'ar-SA', label: 'Arabic (Saudi Arabia)', flag: '🇸🇦', nativeName: 'العربية' },
  { id: 'it-IT', label: 'Italian (Italy)', flag: '🇮🇹', nativeName: 'Italiano' },
  { id: 'tr-TR', label: 'Turkish (Turkey)', flag: '🇹🇷', nativeName: 'Türkçe' },
  { id: 'ru-RU', label: 'Russian (Russia)', flag: '🇷🇺', nativeName: 'Русский' },
  { id: 'id-ID', label: 'Indonesian (Indonesia)', flag: '🇮🇩', nativeName: 'Bahasa Indonesia' },
];

export const VOICE_PERSONAS: VoicePersona[] = [
  // =========================================================================
  // 1. ENGLISH (US) - 10 Male & 10 Female Personas
  // =========================================================================
  {
    id: 'en-us-male-1',
    name: 'Guy (Narrator)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American General',
    description: 'Dynamic Studio Host • Deep & Confident Adult Male',
    previewPhrase: 'Welcome everyone! Get ready for your first trivia challenge.',
    edgeVoiceName: 'en-US-GuyNeural',
  },
  {
    id: 'en-us-male-2',
    name: 'Christopher (Deep)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Deep',
    description: 'Deep Resonant Broadcast Voice • Rich Baritone Male',
    previewPhrase: 'Listen carefully to the question, and lock in your answer.',
    edgeVoiceName: 'en-US-ChristopherNeural',
  },
  {
    id: 'en-us-male-3',
    name: 'Eric (Energetic)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Energetic',
    description: 'Energetic Game Show Host • Clear & Punchy Voice',
    previewPhrase: 'The clock is ticking down fast! Make your choice right now.',
    edgeVoiceName: 'en-US-EricNeural',
  },
  {
    id: 'en-us-male-4',
    name: 'Roger (Classic)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Classic',
    description: 'Warm & Authoritative Speaker • Balanced Delivery',
    previewPhrase: 'Let us see if you managed to find the correct answer.',
    edgeVoiceName: 'en-US-RogerNeural',
  },
  {
    id: 'en-us-male-5',
    name: 'Steffan (Crisp)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Crisp',
    description: 'Smooth Professional Voice • Clean Studio Pronunciation',
    previewPhrase: 'Outstanding performance! That is one hundred percent correct.',
    edgeVoiceName: 'en-US-SteffanNeural',
  },
  {
    id: 'en-us-male-6',
    name: 'Andrew (Warm)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Warm',
    description: 'Friendly & Engaging Quizmaster • Natural Conversational Tone',
    previewPhrase: 'You are doing great! Let us move on to the next exciting round.',
    edgeVoiceName: 'en-US-AndrewNeural',
  },
  {
    id: 'en-us-male-7',
    name: 'Brian (Bold)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Bold',
    description: 'Bold & Direct Announcer • High Clarity & Impact',
    previewPhrase: 'Final five seconds remaining! What is your final guess?',
    edgeVoiceName: 'en-US-BrianNeural',
  },
  {
    id: 'en-us-male-8',
    name: 'Jason (Smooth)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Smooth',
    description: 'Modern & Articulate Narrator • Relaxed Studio Cadence',
    previewPhrase: 'Fantastic intuition! You nailed that challenging question.',
    edgeVoiceName: 'en-US-JasonNeural',
  },
  {
    id: 'en-us-male-9',
    name: 'Davis (Documentary)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Documentary',
    description: 'Insightful & Calibrated • Documentary Knowledge Host',
    previewPhrase: 'Here is an interesting fact behind this historic question.',
    edgeVoiceName: 'en-US-DavisNeural',
  },
  {
    id: 'en-us-male-10',
    name: 'Tony (TV Special)',
    gender: 'male',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American TV Special',
    description: 'Prime-Time TV Showman • High Energy & Excitement',
    previewPhrase: 'Are you ready for the bonus jackpot round? Here we go!',
    edgeVoiceName: 'en-US-TonyNeural',
  },

  // US FEMALE (10)
  {
    id: 'en-us-female-1',
    name: 'Jenny (Natural)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Natural',
    description: 'Warm & Natural Presenter • Melodious Adult Female Voice',
    previewPhrase: 'Awesome job! Let us find out the correct answer together.',
    edgeVoiceName: 'en-US-JennyNeural',
  },
  {
    id: 'en-us-female-2',
    name: 'Aria (Expressive)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Expressive',
    description: 'Polished Broadcast Host • Bright & Articulate Voice',
    previewPhrase: 'Bingo! That is the right answer. You are doing fantastic!',
    edgeVoiceName: 'en-US-AriaNeural',
  },
  {
    id: 'en-us-female-3',
    name: 'Ava (Clear)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Crystal',
    description: 'Crystal-Clear Studio Narrator • Refined & Crisp Voice',
    previewPhrase: 'Congratulations, that was spot on! Moving to the next round.',
    edgeVoiceName: 'en-US-AvaNeural',
  },
  {
    id: 'en-us-female-4',
    name: 'Emma (Friendly)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Friendly',
    description: 'Friendly & Expressive Voice • Warm & Engaging Presence',
    previewPhrase: 'Are you ready for the next round of exciting trivia questions?',
    edgeVoiceName: 'en-US-EmmaNeural',
  },
  {
    id: 'en-us-female-5',
    name: 'Michelle (Upbeat)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Upbeat',
    description: 'Vibrant Quizmaster • Cheerful and Confident Delivery',
    previewPhrase: 'Yes! That choice was completely accurate. Keep it up!',
    edgeVoiceName: 'en-US-MichelleNeural',
  },
  {
    id: 'en-us-female-6',
    name: 'Sara (Professional)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Professional',
    description: 'Authoritative News & Quiz Host • Steady & Polished',
    previewPhrase: 'Let us examine all the choices carefully before deciding.',
    edgeVoiceName: 'en-US-SaraNeural',
  },
  {
    id: 'en-us-female-7',
    name: 'Jane (Enthusiastic)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Dynamic',
    description: 'High Spirits & Fun • Engaging Community Host',
    previewPhrase: 'Whoa, you are on an incredible winning streak right now!',
    edgeVoiceName: 'en-US-JaneNeural',
  },
  {
    id: 'en-us-female-8',
    name: 'Nancy (Warm)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Warm',
    description: 'Soothing Storyteller & Educational Host • Gentle Tone',
    previewPhrase: 'Here is a fascinating breakdown of how this answer works.',
    edgeVoiceName: 'en-US-NancyNeural',
  },
  {
    id: 'en-us-female-9',
    name: 'Amber (Modern)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Modern',
    description: 'Contemporary & Chic • Upbeat Podcast & Reel Host',
    previewPhrase: 'Drop your guesses in the comments and let us check the scoreboard!',
    edgeVoiceName: 'en-US-AmberNeural',
  },
  {
    id: 'en-us-female-10',
    name: 'Ashley (Radiant)',
    gender: 'female',
    language: 'en-US',
    languageLabel: 'English (US)',
    flag: '🇺🇸',
    accent: 'American Radiant',
    description: 'Bright & Charismatic Voice • Perfect for Viral Quizzes',
    previewPhrase: 'Phenomenal speed! You answered that in record time.',
    edgeVoiceName: 'en-US-AshleyNeural',
  },

  // =========================================================================
  // 2. ENGLISH (UK) - 10 Male & 10 Female Personas
  // =========================================================================
  {
    id: 'en-gb-male-1',
    name: 'Ryan (British Host)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British BBC',
    description: 'Classic British Broadcast Voice • Rich & Distinguished',
    previewPhrase: 'Splendid work everyone! Let us reveal the correct answer.',
    edgeVoiceName: 'en-GB-RyanNeural',
  },
  {
    id: 'en-gb-male-2',
    name: 'Thomas (Resonant)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Oxbridge',
    description: 'Deep & Cultured Delivery • Scholarly Quiz Master',
    previewPhrase: 'Consider the options with care, time is slipping away.',
    edgeVoiceName: 'en-GB-ThomasNeural',
  },
  {
    id: 'en-gb-male-3',
    name: 'Alfie (Energetic)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Modern',
    description: 'Lively Modern Brit • Upbeat & Engaging Delivery',
    previewPhrase: 'Top marks! That was an absolutely brilliant answer.',
    edgeVoiceName: 'en-GB-AlfieNeural',
  },
  {
    id: 'en-gb-male-4',
    name: 'Elliot (Crisp)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Contemporary',
    description: 'Refined & Articulate Narrator • Balanced Clarity',
    previewPhrase: 'Here is your next question, prepare yourselves.',
    edgeVoiceName: 'en-GB-ElliotNeural',
  },
  {
    id: 'en-gb-male-5',
    name: 'Noah (Warm)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Friendly',
    description: 'Friendly & Welcoming Voice • Smooth Tone',
    previewPhrase: 'Marvellous effort! Let us see how the scores are looking.',
    edgeVoiceName: 'en-GB-NoahNeural',
  },
  {
    id: 'en-gb-male-6',
    name: 'Oliver (Academic)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Academic',
    description: 'Intellectual & Measured • University Quiz Master',
    previewPhrase: 'An excellent deduction. That is indeed the correct answer.',
    edgeVoiceName: 'en-GB-OliverNeural',
  },
  {
    id: 'en-gb-male-7',
    name: 'Ethan (London)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'London Contemporary',
    description: 'Vibrant City Tone • Quick Wit and Style',
    previewPhrase: 'Locked in your answer? Let us see if you were right!',
    edgeVoiceName: 'en-GB-RyanNeural',
  },
  {
    id: 'en-gb-male-8',
    name: 'George (Royal)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Formal',
    description: 'Stately & Formal Announcer • Deep Projection',
    previewPhrase: 'We now present the grand question of this round.',
    edgeVoiceName: 'en-GB-ThomasNeural',
  },
  {
    id: 'en-gb-male-9',
    name: 'Arthur (Gentle)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Gentle',
    description: 'Calm & Reassuring Narrator • Steady Delivery',
    previewPhrase: 'Take your time, analyze each clue thoughtfully.',
    edgeVoiceName: 'en-GB-ElliotNeural',
  },
  {
    id: 'en-gb-male-10',
    name: 'Harry (Game Host)',
    gender: 'male',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Game Show',
    description: 'Fast-Paced Quiz Showman • Energetic & Punchy',
    previewPhrase: 'Three, two, one, and time is up! What did you pick?',
    edgeVoiceName: 'en-GB-AlfieNeural',
  },

  // UK FEMALE (10)
  {
    id: 'en-gb-female-1',
    name: 'Sonia (Melodious)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Melodious',
    description: 'Sophisticated & Melodious Voice • Polished BBC Tone',
    previewPhrase: 'Brilliant! You found the exact correct answer right away.',
    edgeVoiceName: 'en-GB-SoniaNeural',
  },
  {
    id: 'en-gb-female-2',
    name: 'Libby (Clear)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Clear',
    description: 'Crystal Clear British Delivery • Bright & Professional',
    previewPhrase: 'Well done! Moving straight along to the next round.',
    edgeVoiceName: 'en-GB-LibbyNeural',
  },
  {
    id: 'en-gb-female-3',
    name: 'Abbi (Expressive)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Expressive',
    description: 'Warm & Cheerful British Host • Natural Cadence',
    previewPhrase: 'Spot on! That is one hundred percent right.',
    edgeVoiceName: 'en-GB-AbbiNeural',
  },
  {
    id: 'en-gb-female-4',
    name: 'Hollie (Friendly)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Friendly',
    description: 'Approachable & Engaging Speaker • Smooth & Gentle',
    previewPhrase: 'Let us see how many of you got that tricky question right.',
    edgeVoiceName: 'en-GB-HollieNeural',
  },
  {
    id: 'en-gb-female-5',
    name: 'Mia (Upbeat)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Upbeat',
    description: 'Lively Modern Presenter • High Spirit & Energy',
    previewPhrase: 'Superb! You are on absolute fire with these answers.',
    edgeVoiceName: 'en-GB-MiaNeural',
  },
  {
    id: 'en-gb-female-6',
    name: 'Bella (Refined)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Elegant',
    description: 'Elegant & Cultured Host • High Clarification',
    previewPhrase: 'A truly splendid choice, well done indeed.',
    edgeVoiceName: 'en-GB-SoniaNeural',
  },
  {
    id: 'en-gb-female-7',
    name: 'Ada (Documentary)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Narrative',
    description: 'Insightful Science & History Host • Clear & Engaging',
    previewPhrase: 'Here is why this fact remains one of the most famous in history.',
    edgeVoiceName: 'en-GB-LibbyNeural',
  },
  {
    id: 'en-GB-female-8',
    name: 'Ruby (Modern)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Contemporary',
    description: 'Fresh & Relatable • Popular Social Media Host',
    previewPhrase: 'Drop your thoughts below and see if you beat the timer!',
    edgeVoiceName: 'en-GB-AbbiNeural',
  },
  {
    id: 'en-gb-female-9',
    name: 'Freya (Radiant)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Radiant',
    description: 'Inspiring & Enthusiastic Tone • Clear High Resonance',
    previewPhrase: 'Fantastic deduction! You navigated that beautifully.',
    edgeVoiceName: 'en-GB-HollieNeural',
  },
  {
    id: 'en-gb-female-10',
    name: 'Emily (Game Master)',
    gender: 'female',
    language: 'en-GB',
    languageLabel: 'English (UK)',
    flag: '🇬🇧',
    accent: 'British Game Show',
    description: 'Fast & Thrilling Quiz Master • High Drama & Excitement',
    previewPhrase: 'The tension is building! Let us reveal the winner!',
    edgeVoiceName: 'en-GB-MiaNeural',
  },

  // =========================================================================
  // 3. URDU (PAKISTAN) - 10 Male & 10 Female Personas
  // =========================================================================
  {
    id: 'ur-pk-male-1',
    name: 'Asad (اسد)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Broadcast Standard',
    description: 'پیشہ ورانہ ٹی وی میزبان • پروقار اور دلنشین آواز',
    previewPhrase: 'خوش آمدید! آئیے دیکھتے ہیں کہ اس سوال کا صحیح جواب کیا ہے۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-2',
    name: 'Tariq (طارق)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Classic',
    description: 'سنجیدہ اور گہری آواز • علمی اور معلوماتی کوئز کے لیے بہترین',
    previewPhrase: 'سوال پر غور فرمائیں اور وقت ختم ہونے سے پہلے جواب چنیں۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-3',
    name: 'Bilal (بلال)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Energetic',
    description: 'پرجوش گیم شو ہوسٹ • تیز اور متحرک انداز',
    previewPhrase: 'شاباش! آپ کا جواب بالکل درست اور بروقت تھا۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-4',
    name: 'Hamza (حمزہ)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Warm',
    description: 'دوستانہ اور پرکشش لہجہ • روانی اور واضح تلفظ',
    previewPhrase: 'آئیے اگلے دلچسپ سوال کی طرف بڑھتے ہیں۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-5',
    name: 'Usman (عثمان)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Clear',
    description: 'صاف اور کرسٹل آواز • مستحکم اور قابل اعتماد انداز',
    previewPhrase: 'بہترین کارکردگی! آپ نے سو فیصد درست جواب دیا۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-6',
    name: 'Farhan (فرحان)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Modern',
    description: 'جدید اور متحرک پیش کار • سوشل میڈیا ویڈیوز کے لیے بہترین',
    previewPhrase: 'کیا آپ تیار ہیں اگلے زبردست راؤنڈ کے لیے؟',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-7',
    name: 'Imran (عمران)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Bold',
    description: 'باوقار اور مضبوط گرجدار آواز • کوئز چیمپئن شپ',
    previewPhrase: 'وقت تیزی سے گزر رہا ہے، جلد فیصلہ کیجیے!',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-8',
    name: 'Zaid (زید)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Smooth',
    description: 'نرم اور میٹھا لہجہ • تعلیمی اور معلوماتی اسباق',
    previewPhrase: 'اس تاریخی حقیقت کو جان کر آپ حیران رہ جائیں گے۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-9',
    name: 'Danish (دانش)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Dynamic',
    description: 'تیز فہم اور ہوشیار اینکر • کوئز ماسٹر',
    previewPhrase: 'لاجواب! آپ کے اسکور میں شاندار اضافہ ہوا ہے۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },
  {
    id: 'ur-pk-male-10',
    name: 'Ali (علی)',
    gender: 'male',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Classic Radio',
    description: 'کلاسیک ریڈیو اناؤنسر • روایتی اردو ادب اور کوئز',
    previewPhrase: 'ناظرین کرام، ملاحظہ فرمائیے اگلا دلچسپ مرحلہ۔',
    edgeVoiceName: 'ur-PK-AsadNeural',
  },

  // URDU FEMALE (10)
  {
    id: 'ur-pk-female-1',
    name: 'Uzma (عظمیٰ)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Sweet Melodious',
    description: 'پیشہ ورانہ نیوز کاسٹر • سریلی اور پرکشش نسوانی آواز',
    previewPhrase: 'شاباش! آپ کا انتخاب بالکل صحیح تھا، بہت خوب۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-2',
    name: 'Ayesha (عائشہ)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Articulate',
    description: 'صاف تلفظ اور روانی • تعلیمی اور معلوماتی پروگرام',
    previewPhrase: 'سوچیے اور درست آپشن کا انتخاب کیجیے۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-3',
    name: 'Fatima (فاطمہ)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Warm Host',
    description: 'دوستانہ اور پرجوش اینکر • ٹی وی کوئز شو',
    previewPhrase: 'مبارک ہو! آپ نے اس سوال کا صحیح جواب دے دیا ہے۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-4',
    name: 'Zainab (زینب)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Gentle',
    description: 'نرم اور شائستہ لہجہ • اسلامی اور معلوماتی کوئز',
    previewPhrase: 'آئیے دیکھتے ہیں کہ اس سوال کے پیچھے کیا اہم معلومات ہیں۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-5',
    name: 'Maryam (مریم)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Bright',
    description: 'روشن اور بااعتماد آواز • نوجوان سامعین کے لیے بہترین',
    previewPhrase: 'بہت اچھے! آئیے اگلے دلچسپ سوال کی جانب بڑھتے ہیں۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-6',
    name: 'Hina (حنا)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Energetic',
    description: 'پرجوش اور تیز رفتار • گیم شو پریزینٹر',
    previewPhrase: 'ٹائمر ختم ہونے والا ہے، اپنا جواب لاک کیجیے!',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-7',
    name: 'Sana (ثناء)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Modern',
    description: 'جدید پوڈکاسٹ اور شارٹس کے لیے پرکشش انداز',
    previewPhrase: 'آپ کا اندازہ بالکل درست تھا، لاجواب کوشش۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-8',
    name: 'Sadia (سعدیہ)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Professional',
    description: 'پیشہ ورانہ اور متوازن لہجہ • سائنسی و تاریخی کوئز',
    previewPhrase: 'اس سوال کا تفصیلی جواب ہم ابھی دیکھتے ہیں۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-9',
    name: 'Mahnoor (ماہ نور)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Vibrant',
    description: 'چمکدار اور خوشگوار آواز • تفریحی کوئز',
    previewPhrase: 'واہ! کیا شاندار رفتار سے آپ نے جواب دیا۔',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },
  {
    id: 'ur-pk-female-10',
    name: 'Noor (نور)',
    gender: 'female',
    language: 'ur-PK',
    languageLabel: 'Urdu (Pakistan)',
    flag: '🇵🇰',
    accent: 'Urdu Radiant',
    description: 'متاثر کن اور دلکش انداز • حتمی کوئز راؤنڈ',
    previewPhrase: 'آپ کا یہ اسکور واقعی قابل تعریف ہے، شاندار!',
    edgeVoiceName: 'ur-PK-UzmaNeural',
  },

  // =========================================================================
  // 4. HINDI (INDIA) - 10 Male & 10 Female Personas
  // =========================================================================
  {
    id: 'hi-in-male-1',
    name: 'Madhur (मधुर)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Standard',
    description: 'गंभीर एवं स्पष्ट उद्घोषक • टीवी क्विज होस्ट',
    previewPhrase: 'नमस्कार दोस्तों! आइए देखते हैं कि इस प्रश्न का सही उत्तर क्या है।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-2',
    name: 'Rajesh (राजेश)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Deep',
    description: 'गहरा और आत्मविश्वास से भरा स्वर • सामान्य ज्ञान',
    previewPhrase: 'समय समाप्त होने से पहले अपना विकल्प चुनिए।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-3',
    name: 'Amit (अमित)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Energetic',
    description: 'ऊर्जावान और रोमांचक गेम शो प्रस्तोता',
    previewPhrase: 'शाबाश! आपने बिल्कुल सही उत्तर दिया है।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-4',
    name: 'Vikram (विक्रम)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Authoritative',
    description: 'प्रभावशाली एवं स्पष्ट उच्चारण • प्रतियोगिता विशेषज्ञ',
    previewPhrase: 'आइए अब अगले रोमांचक प्रश्न की ओर बढ़ते हैं।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-5',
    name: 'Suresh (सुरेश)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Warm',
    description: 'सरल एवं मधुर स्वर • शैक्षिक क्विज',
    previewPhrase: 'बहुत बढ़िया प्रयास! आपका उत्तर शत-प्रतिशत सही है।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-6',
    name: 'Deepak (दीपक)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Dynamic',
    description: 'आधुनिक एवं आकर्षक शैली • सोशल मीडिया रील्स',
    previewPhrase: 'क्या आप तैयार हैं अगले शानदार प्रश्न के लिए?',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-7',
    name: 'Rahul (राहुल)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Fast-Paced',
    description: 'तेज गति और रोमांच से भरपूर उद्घोषक',
    previewPhrase: 'घड़ी की सुइयां तेजी से चल रही हैं, जल्दी उत्तर दें!',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-8',
    name: 'Manoj (मनोज)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Balanced',
    description: 'संतुलित और विश्वसनीय स्वर • इतिहास एवं विज्ञान',
    previewPhrase: 'इस तथ्य के पीछे का रोचक इतिहास भी हम जानेंगे।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-9',
    name: 'Sanjay (संजय)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Expressive',
    description: 'भावपूर्ण एवं आकर्षक प्रस्तुति • क्विज मास्टर',
    previewPhrase: 'कमाल कर दिया आपने! यह बिल्कुल सटीक उत्तर है।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },
  {
    id: 'hi-in-male-10',
    name: 'Alok (आलोक)',
    gender: 'male',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Grand',
    description: 'भव्य एवं गरिमापूर्ण स्वर • ग्रैंड फिनाले क्विज',
    previewPhrase: 'आइए अब आज के विजेता का फैसला करते हैं।',
    edgeVoiceName: 'hi-IN-MadhurNeural',
  },

  // HINDI FEMALE (10)
  {
    id: 'hi-in-female-1',
    name: 'Swara (स्वरा)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Melodious',
    description: 'मधुर एवं सुरीली टीवी प्रस्तोता • स्पष्ट हिंदी उच्चारण',
    previewPhrase: 'बधाई हो! आपका उत्तर बिल्कुल सही और सटीक है।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-2',
    name: 'Pooja (पूजा)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Articulate',
    description: 'आकर्षक और स्पष्ट स्वर • सामान्य ज्ञान मंच',
    previewPhrase: 'ध्यान से सोचिए और सही विकल्प पर क्लिक कीजिए।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-3',
    name: 'Sunita (सुनीता)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Warm',
    description: 'स्नेहपूर्ण और आत्मीय स्वर • शैक्षिक प्रतियोगिता',
    previewPhrase: 'आइए देखते हैं कि इस कठिन प्रश्न का सही उत्तर क्या है।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-4',
    name: 'Anjali (अंजलि)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Bright',
    description: 'उत्साही एवं चुलबुली शैली • मनोरंजक क्विज',
    previewPhrase: 'वाह! आपने तो रिकॉर्ड समय में सही उत्तर दे दिया।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-5',
    name: 'Shreya (श्रेया)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Soft',
    description: 'कोमल एवं स्पष्ट आवाज • साहित्यिक एवं सांस्कृतिक क्विज',
    previewPhrase: 'बहुत सुंदर! आइए अगले पड़ाव की ओर अग्रसर होते हैं।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-6',
    name: 'Neha (नेहा)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Modern',
    description: 'आधुनिक और तेजतर्रार आवाज • डिजिटल क्विज शो',
    previewPhrase: 'समय पूरा होने वाला है, जल्दी अपना फैसला लॉक करें!',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-7',
    name: 'Ritu (ऋतु)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Balanced',
    description: 'शांत एवं सुदृढ़ शैली • विज्ञान एवं भूगोल',
    previewPhrase: 'इस प्रश्न का सही विश्लेषण हम विस्तार से जानेंगे।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-8',
    name: 'Divya (दिव्या)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Radiant',
    description: 'प्रेरणादायी एवं स्पष्ट स्वर • ज्ञान क्विज',
    previewPhrase: 'शानदार प्रदर्शन! आपके सभी उत्तर सही जा रहे हैं।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-9',
    name: 'Kavita (कविता)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Expressive',
    description: 'कलात्मक एवं सुरुचिपूर्ण लहजा • विशेष क्विज',
    previewPhrase: 'आइए इस रोचक तथ्य को और गहराई से समझें।',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },
  {
    id: 'hi-in-female-10',
    name: 'Aarti (आरती)',
    gender: 'female',
    language: 'hi-IN',
    languageLabel: 'Hindi (India)',
    flag: '🇮🇳',
    accent: 'Hindi Grand',
    description: 'गरिमापूर्ण टीवी उद्घोषिका • अंतिम महा-मुकाबला',
    previewPhrase: 'अंतिम चक्र में आपका स्वागत है, तैयार हो जाइए!',
    edgeVoiceName: 'hi-IN-SwaraNeural',
  },

  // =========================================================================
  // 5. SPANISH (SPAIN) - 10 Male & 10 Female Personas
  // =========================================================================
  {
    id: 'es-es-male-1',
    name: 'Álvaro (Castellano)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Presentador de televisión enérgico y profesional',
    previewPhrase: '¡Bienvenidos al concurso! Prepárense para la primera pregunta.',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-2',
    name: 'Manuel (Profundo)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz profunda y resonante para concursos de cultura general',
    previewPhrase: 'Escuchen con atención y seleccionen su respuesta definitiva.',
    edgeVoiceName: 'es-ES-ManuelNeural',
  },
  {
    id: 'es-es-male-3',
    name: 'Arnau (Dinámico)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Locutor dinámico con ritmo televisivo moderno',
    previewPhrase: '¡El cronómetro está corriendo! Hagan su elección ahora.',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-4',
    name: 'Darío (Clásico)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz templada y pedagógica para documentales y preguntas',
    previewPhrase: 'Veamos si han logrado dar con la opción correcta.',
    edgeVoiceName: 'es-ES-ManuelNeural',
  },
  {
    id: 'es-es-male-5',
    name: 'Elías (Enérgico)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Entusiasta maestro de ceremonias para trivia viral',
    previewPhrase: '¡Excelente deducción! Esa respuesta es cien por cien correcta.',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-6',
    name: 'Nil (Moderno)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Tono juvenil y fresco para vídeos de redes sociales',
    previewPhrase: '¿Preparados para la siguiente ronda de preguntas?',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-7',
    name: 'Saúl (Resonante)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz solemne y elegante para grandes desafíos',
    previewPhrase: 'Quedan solo cinco segundos, decidan su respuesta.',
    edgeVoiceName: 'es-ES-ManuelNeural',
  },
  {
    id: 'es-es-male-8',
    name: 'Teo (Amigable)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz cálida, cercana y de dicción impecable',
    previewPhrase: 'Han hecho un trabajo magnífico hasta este momento.',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-9',
    name: 'Pol (Rápido)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Cadencia veloz para rondas relámpago de preguntas',
    previewPhrase: '¡Tres, dos, uno y tiempo! Comprobemos el resultado.',
    edgeVoiceName: 'es-ES-AlvaroNeural',
  },
  {
    id: 'es-es-male-10',
    name: 'Mateo (Gala)',
    gender: 'male',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Locución de gala para la gran final del concurso',
    previewPhrase: 'Descubramos quién se corona como el campeón definitivo.',
    edgeVoiceName: 'es-ES-ManuelNeural',
  },

  // ES FEMALE (10)
  {
    id: 'es-es-female-1',
    name: 'Elvira (Natural)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz melódica, clara y natural de presentadora de TV',
    previewPhrase: '¡Fantástico trabajo! Descubramos la solución juntos.',
    edgeVoiceName: 'es-ES-ElviraNeural',
  },
  {
    id: 'es-es-female-2',
    name: 'Abril (Brillante)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Presentadora brillante, articulada y con gran energía',
    previewPhrase: '¡Bingo! Esa es exactamente la respuesta acertada.',
    edgeVoiceName: 'es-ES-AbrilNeural',
  },
  {
    id: 'es-es-female-3',
    name: 'Estrella (Clara)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Locución nítida de estudio con elegancia natural',
    previewPhrase: 'Enhorabuena, han acertado de pleno en esta pregunta.',
    edgeVoiceName: 'es-ES-ElviraNeural',
  },
  {
    id: 'es-es-female-4',
    name: 'Irene (Amable)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz cálida y expresiva para contenidos educativos',
    previewPhrase: '¿Están listos para afrontar el siguiente reto?',
    edgeVoiceName: 'es-ES-AbrilNeural',
  },
  {
    id: 'es-es-female-5',
    name: 'Laia (Enérgica)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz viva y entusiasta para juegos y pasatiempos',
    previewPhrase: '¡Sí! Su elección ha sido completamente acertada.',
    edgeVoiceName: 'es-ES-ElviraNeural',
  },
  {
    id: 'es-es-female-6',
    name: 'Lía (Moderna)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Estilo contemporáneo para redes y vídeos cortos',
    previewPhrase: 'Dejen su respuesta en los comentarios y sigamos jugando.',
    edgeVoiceName: 'es-ES-AbrilNeural',
  },
  {
    id: 'es-es-female-7',
    name: 'Noa (Pedagógica)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Tono pausado y didáctico para ciencia e historia',
    previewPhrase: 'Aquí tienen la explicación detallada de este hecho histórico.',
    edgeVoiceName: 'es-ES-ElviraNeural',
  },
  {
    id: 'es-es-female-8',
    name: 'Triana (Radiante)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Voz luminosa y carismática para concursos familiares',
    previewPhrase: '¡Impresionante racha de aciertos! Continúen así.',
    edgeVoiceName: 'es-ES-AbrilNeural',
  },
  {
    id: 'es-es-female-9',
    name: 'Vera (Elegante)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Elocución refinada y sofisticada de alta fidelidad',
    previewPhrase: 'Examinemos todas las alternativas antes de desvelar el enigma.',
    edgeVoiceName: 'es-ES-ElviraNeural',
  },
  {
    id: 'es-es-female-10',
    name: 'Paloma (Gala)',
    gender: 'female',
    language: 'es-ES',
    languageLabel: 'Spanish (Spain)',
    flag: '🇪🇸',
    accent: 'Español Peninsular',
    description: 'Presentadora estelar para el desenlace del programa',
    previewPhrase: '¡Llegamos al momento decisivo! Descubran la puntuación.',
    edgeVoiceName: 'es-ES-AbrilNeural',
  },
];
